version: '3.7'

networks:
  dev:
    external: true
    name: fabric_dev

services:
  cli:
    image: hyperledger/fabric-tools:latest
    container_name: org1.cli
    tty: true
    stdin_open: true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ROOTCERT_FILE=/e tc/hyperledger/fabric/tls-msp/tlscacerts/tls-localhost-10054.pem
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=org1.peer1:7050
    volumes:
      - ../organizations/org1/peers/peer1:/etc/hyperledger/fabric
      - ../organizations/org1/peers/config:/etc/hyperledger/config
      - /home/vboxuser/fabric/bin:/usr/local/bin
    networks:
      - dev
